### PR TITLE
Update ToDo.md

### PR DESCRIPTION
**Pull request by trytomakeyouprivate**

### CODE REVIEW

**Comment by iaacornus** [comment]
where did the original repo go?

**Comment by trytomakeyouprivate** [comment]
@iaacornus I think I ran into a pull issue because of too many differences, so I deleted it and just forked yours. Pretty new to Github, got something lost?

**Comment by iaacornus** [comment]
> @iaacornus I think I ran into a pull issue because of too many differences, so I deleted it and just forked yours. Pretty new to Github, got something lost?

yes I created an issue named development tracker in the original repo which contains lists of things to do.

**Comment by trytomakeyouprivate** [comment]
Oh sorry for that. Can you recover it?

To the bash vs. python thing, lets try it in python, no problem on Kionite, preinstalled and stuff. Easy to use, light processes, if it works I cant find any reason not to use it.

**Comment by iaacornus** [comment]
unfortunately not, perhaps you can check it? the issue is titled development tracker with lists in it

**Comment by iaacornus** [comment]
> To the bash vs. python thing, lets try it in python, no problem on Kionite, preinstalled and stuff. Easy to use, light processes, if it works I cant find any reason not to use it.

sure, I've already had a works on gpu installation and third repo install, although i havent tested it yet. Any ideas about options in cli?

**Pull request merged**
